
package cop5556sp17;

import java.io.FileOutputStream;
import java.io.OutputStream;

import org.junit.After;
import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

import cop5556sp17.AST.ASTNode;
import cop5556sp17.AST.Program;

public class CodeGenVisitorTest {

	static final boolean doPrint = true;

	static void show(Object s) {
		if (doPrint) {
			System.out.println(s);
		}
	}

	boolean devel = false;
	boolean grade = true;

	@Before
	public void initLog() {

		if (devel || grade)
			PLPRuntimeLog.initLog();

	}

	@After
	public void printLog() {

		System.out.println(PLPRuntimeLog.getString());

	}

	@Test
	public void emptyProg() throws Exception {
		// scan, parse, and type check the program

		String progname = "LQTest ";
		String input = progname
				+ "file file1,file file2,file outputFile,url url1,url url2{\n"
				+ "image img1 image img2 frame frame1\n"
				+ "url1->img1->frame1->show;"
				
				+ "}\n";

		Scanner scanner = new Scanner(input);
		scanner.scan();
		Parser parser = new Parser(scanner);
		ASTNode program = parser.parse();
		TypeCheckVisitor v = new TypeCheckVisitor();
		program.visit(v, null);

		show(program);

		// generate code
		CodeGenVisitor cv = new CodeGenVisitor(devel, grade, null);
		byte[] bytecode = (byte[]) program.visit(cv, null);

		// output the generated bytecode
		CodeGenUtils.dumpBytecode(bytecode);

		// write byte code to file
		String name = ((Program) program).getName();
		String classFileName = "bin/" + name + ".class";
		OutputStream output = new FileOutputStream(classFileName);
		output.write(bytecode);
		output.close();
		System.out.println("wrote classfile to " + classFileName);

		// directly execute bytecode
		String[] args = new String[9]; // create command line argument array to
										// initialize params, none in this case

		args[0] = "Images/image1.jpg";
		args[1] = "Images/image2.jpg";
		args[2] = "Images/output1.jpg";
		args[3] = "Images/image1.jpg";
		args[4] = "Images/image1.jpg";

		Runnable instance = CodeGenUtils.getInstance(name, bytecode, args);
		instance.run();
	}

}
